Civil-Service-Human-Resources/identity-service

README.md
build.gradle
src/main/java/uk/gov/cshr/config/ManagementSecurityConfig.java
src/main/java/uk/gov/cshr/config/SecurityConfig.java
src/main/java/uk/gov/cshr/config/UserSecurityConfig.java
src/main/java/uk/gov/cshr/controller/InviteController.java
src/main/java/uk/gov/cshr/controller/SignupController.java
src/main/java/uk/gov/cshr/dto/IdentityDTO.java
src/main/java/uk/gov/cshr/repository/IdentityRepository.java
src/main/java/uk/gov/cshr/repository/InviteRepository.java
src/main/java/uk/gov/cshr/service/InviteService.java
src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/main/resources/application.yml
src/main/resources/templates/inviteList.html
src/main/resources/templates/management-login.html
src/main/resources/templates/signup.html
src/main/resources/templates/signupSuccess.html
src/test/java/uk.gov.cshr/controller/InviteControllerTest.java
src/test/java/uk/gov/cshr/repository/InviteRepositoryTest.java
src/test/java/uk/gov/cshr/service/InviteServiceTest.java
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java
src/test/resources/application.yml

- Refactoring and fixing failing tests as per PR comments from https://github.com/Civil-Service-Human-Resources/oauth2-stub/pull/23

chore/refactoring and PR cleanup

---

README.md
src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/main/resources/templates/reset/requestReset.html
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java

- Fixing error on signup (when new identity was being created there was an issue with sharing the roles between Identity and Invite tables)
- Fixing styling on Reset screen to be more consistent and to match mockups 
- Updating README

LPFG-269/fixing readme, styling reset screen and updating readme

---

src/main/resources/db/migration/h2/V1.1__data.sql
src/main/resources/db/migration/mysql/V1.2.3__add-organisation-manager-role.sql

- adding db migrations to add new ORGANISATION_MANAGER role
- giving `learner@domain.com` necessary roles for local dev

LPFG-937: db migration for adding new org manager roles

---

src/main/resources/application.yml

- update app.yml to take env vars for invite, resets and access tokens
- update default invite value to be 259200s/3 days

LPFG-1021: Update invite expiration

---

src/main/resources/templates/fragments/user-header.html

Changed phase banner content to match LPG-UI

LPFG-1094 change phase banner contents

---

src/main/java/uk/gov/cshr/controller/IdentityController.java
src/main/resources/templates/identityList.html
src/main/resources/templates/updateIdentity.html
src/test/java/uk.gov.cshr/controller/IdentityControllerTest.java

- Added locked param and set locked in identityUpdate function in IdentityController.java
- Added disabled locked tickbox row in identityList.html
- Added locked tickbox row in updateIdentity.html

LPFG-1177: Account Unlock

---

src/main/resources/templates/login.html
src/main/resources/templates/management-login.html
src/main/resources/templates/reset/requestReset.html

- change page title from login to sign in
- add padding to cancel

LPFG-1163 / LPFG-1164 gds udpates

---

src/main/resources/templates/fragments/user-footer.html
src/main/resources/templates/login.html

Updated the footer to be consistent with the rest of the services.

LC-113: Contact us page

---

src/main/java/uk/gov/cshr/controller/ListIdentitiesController.java
src/main/java/uk/gov/cshr/repository/IdentityRepository.java

- endpoint to get identities map for reporting

LC-180-identities-map-api

---

src/main/java/uk/gov/cshr/config/UserSecurityConfig.java
src/main/java/uk/gov/cshr/controller/RevokeTokenEndpoint.java

LC-163: mgmt-login-issues

---

src/main/java/uk/gov/cshr/controller/ListIdentitiesController.java
src/main/java/uk/gov/cshr/dto/IdentityDTO.java
src/main/java/uk/gov/cshr/repository/IdentityRepository.java

LC-221: identity-map-performance

---

src/main/java/uk/gov/cshr/controller/AuthenticationController.java
src/main/java/uk/gov/cshr/controller/reset/ResetController.java
src/main/java/uk/gov/cshr/domain/Identity.java
src/main/java/uk/gov/cshr/repository/IdentityRepository.java
src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/main/resources/application.yml
src/main/resources/db/migration/h2/V1.1__data.sql
src/main/resources/db/migration/h2/V1__init.sql
src/main/resources/db/migration/mysql/V1.4.1__add-last-logged-in.sql
src/test/java/uk.gov.cshr/controller/IdentityControllerTest.java
src/test/java/uk.gov.cshr/controller/ResetControllerTest.java
src/test/java/uk/gov/cshr/repository/IdentityRepositoryTest.java
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java

- cut over from https://github.com/Civil-Service-Human-Resources/identity-service/pull/90
- update identity to include last logged in and deletion notification attributes

LPFG-1188: updating identity domain to include last logged in

---

src/main/java/uk/gov/cshr/config/AuthorisationServerConfiguration.java
src/main/java/uk/gov/cshr/config/ServerConfig.java
src/main/resources/db/migration/h2/V1.2__oauth_code.sql
src/main/resources/db/migration/mysql/V1.6.0__add-oath-token-table.sql

- added migration files for oauth_code tables (h2 & mysql)
- configured JdbcAuthorizationCodeServices as authorizationCodeServices

Implemented auth codes in mysql (instead of in-memory)

---

src/main/java/uk/gov/cshr/controller/AccountController.java
src/main/java/uk/gov/cshr/service/CsrsService.java
src/main/java/uk/gov/cshr/service/EmailUpdateService.java
src/main/resources/application.yml
src/test/java/uk.gov.cshr/controller/AccountControllerTest.java
src/test/java/uk/gov/cshr/service/CsrsServiceTest.java
src/test/java/uk/gov/cshr/service/EmailUpdateServiceTest.java
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java

Fixes for all the issues to do with the change email on profile page scenario.

Bugfix lc 14 find old org code

---

.gitignore
src/main/java/uk/gov/cshr/controller/CustomErrorController.java
src/main/java/uk/gov/cshr/controller/LoginController.java
src/main/resources/application.yml
src/main/resources/templates/404.html
src/main/resources/templates/500.html
src/main/resources/templates/error.html

Error-management-identity-service

LC-432 Disable springboot default white label and display user friendly error pages

---

src/main/java/uk/gov/cshr/controller/CustomErrorController.java
src/main/java/uk/gov/cshr/controller/utils/ErrorPageMap.java
src/main/resources/templates/400.html
src/main/resources/templates/401.html
src/main/resources/templates/403.html
src/main/resources/templates/404.html
src/main/resources/templates/500.html
src/main/resources/templates/error.html

Fixing custom error controller and introduced 4XX pages.

Fix error mapping and introduce 4XX pages

---

src/main/resources/db/migration/mysql/V1.7.1__modified-clear-duplicate.sql

Remove unused variable from the stored procedure

Modified stored procedure to clear duplicate tokens

---

src/main/java/uk/gov/cshr/config/UserSecurityConfig.java
src/main/java/uk/gov/cshr/controller/CustomErrorController.java
src/main/java/uk/gov/cshr/controller/utils/ErrorPageMap.java
src/main/resources/application.yml
src/main/resources/templates/400.html
src/main/resources/templates/401.html
src/main/resources/templates/403.html
src/main/resources/templates/404.html
src/main/resources/templates/500.html
src/main/resources/templates/error.html

Decommissioning the customerrorcontroller to let thymeleaf pick up error content

LC-469-Hotfix

---

src/main/java/uk/gov/cshr/config/UserSecurityConfig.java
src/main/java/uk/gov/cshr/controller/CustomErrorController.java
src/main/java/uk/gov/cshr/controller/utils/ErrorPageMap.java
src/main/resources/application.yml
src/main/resources/templates/400.html
src/main/resources/templates/401.html
src/main/resources/templates/403.html
src/main/resources/templates/404.html
src/main/resources/templates/500.html
src/main/resources/templates/error.html

* LC-562-hotfix
* Changing the behaviour of logout to redirect users to login if no returnTo param is set
Co-authored-by: Will Hamill <william.hamill@gmail.com>

https://cshrdigitalandanalysis.atlassian.net/browse/LC-562 (#152)

---

src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/main/resources/templates/login.html

Merging with new internal develop branch

Lc 276 self service account unlocking

---

src/main/resources/db/migration/mysql/V1.7.1__modified-clear-duplicate.sql

Fix for Flyway issue on integration.  1.7.1 sql file was missing.

SP fix for duplicate tokens

---

src/main/java/uk/gov/cshr/controller/signup/SignupController.java
src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java

Adding additional logic to signup flow to ensure a user is agency, whitelisted or invited

hotfix: adding logic to sign up flow

---

src/main/java/uk/gov/cshr/controller/account/reactivation/ReactivationController.java
src/test/java/uk/gov/cshr/controller/account/reactivation/ReactivationControllerTest.java

Adding condition reordering of agency whitelist for reactivation

hotfix: adding condition reordering of agency whitelist for reactivation

---

src/main/java/uk/gov/cshr/service/NotifyServiceImpl.java

- undo change to set logging level of statement as `debug`

hotfix - undo logging changes

---

src/main/resources/db/migration/mysql/V1.9.3__token-table-status-index.sql

…en fetch and duplicate remediation job queries (#185)

Rebasing the idt-develop branch against the latest master branch

---

src/main/resources/application.yml

Updated the variable name to DURATION_AFTER_REREG_ALLOWED

idt-develop-release-1.0-defect-fix

---

src/main/resources/application.yml

Update variable to DURATION_AFTER_REREG_ALLOWED

idt-release-1.0-defect-fix

---

src/main/java/uk/gov/cshr/repository/InviteRepository.java
src/main/resources/application.yml
src/main/resources/static/assets/css/main.css
src/main/resources/templates/requestInvite.html
src/test/resources/application.yml

Feature lc 314 new user accounts pending to idt-release-1.0

Feature lc 314 new user accounts pending to idt-release-1.0

---

src/main/java/uk/gov/cshr/controller/signup/SignupController.java
src/test/java/uk/gov/cshr/controller/signup/SignupControllerTest.java

A fix for user account pending issue.

Lc 840 user account pending fix

---

src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java

A fix for case sensitive domain name.

lc-841-email-caseinsensitive

---

src/main/resources/templates/reset/checkEmail.html

- Updated email address on the 'check your email' screen

replaced email address

---

.bash_history
.gitignore
Dockerfile
src/main/java/uk/gov/cshr/config/CustomAuthenticationFailureHandler.java
src/main/java/uk/gov/cshr/controller/account/reactivation/ReactivationController.java
src/main/java/uk/gov/cshr/exception/PendingReactivationExistsException.java
src/main/java/uk/gov/cshr/exception/ReactivationRequestExpiredException.java
src/main/java/uk/gov/cshr/repository/ReactivationRepository.java
src/main/java/uk/gov/cshr/service/ReactivationService.java
src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/main/java/uk/gov/cshr/utils/TextEncryptionUtils.java
src/main/resources/templates/login.html
src/test/java/uk/gov/cshr/controller/account/reactivation/ReactivationControllerTest.java
src/test/java/uk/gov/cshr/repository/ReactivationRepositoryTest.java
src/test/java/uk/gov/cshr/service/ReactivationServiceTest.java
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java

This change:
* Adds a check to see if a reactivation request has expired (is still pending and has been requested over 1 day ago)
* Creates a new message to inform user that a linked request from an email has expired
* Prompts the user to send another reactivation request if current one has expired

Set expiry date for reactivation requests

---

src/main/resources/application.yml

This change updates the `application.yml` file by moving the `---` line.

LC-1866: Update application.yml file

---

.run/identity-service [bootRun].run.xml
src/main/java/uk/gov/cshr/controller/account/email/ChangeEmailController.java
src/main/java/uk/gov/cshr/domain/Identity.java
src/main/java/uk/gov/cshr/service/CompoundRoleRepository.java
src/main/java/uk/gov/cshr/service/CompoundRoleRepositoryImpl.java
src/main/java/uk/gov/cshr/service/CsrsService.java
src/main/java/uk/gov/cshr/service/EmailUpdateService.java
src/main/java/uk/gov/cshr/service/security/IdentityClientTokenService.java
src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/main/java/uk/gov/cshr/service/security/OAuthToken.java
src/main/resources/application.yml
src/test/java/uk/gov/cshr/service/CsrsServiceTest.java
src/test/java/uk/gov/cshr/service/EmailUpdateServiceTest.java
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java
src/test/resources/application.yml

- When an email change request is fulfilled
- Remove the user's organisation 
- Remove the user's admin permissions

LC 2475 change email

---

src/main/java/uk/gov/cshr/controller/ListIdentitiesController.java
src/main/java/uk/gov/cshr/domain/Identity.java
src/main/java/uk/gov/cshr/dto/BatchProcessResponse.java
src/main/java/uk/gov/cshr/dto/UidList.java
src/main/java/uk/gov/cshr/repository/IdentityRepository.java
src/main/java/uk/gov/cshr/service/security/IdentityService.java
src/test/java/uk/gov/cshr/repository/IdentityRepositoryTest.java
src/test/java/uk/gov/cshr/service/security/IdentityServiceTest.java
src/test/java/uk/gov/cshr/utils/DataUtils.java

- New endpoint for removing reporting roles from users

LC 2477 Unrestricted organisation / remove reporting roles

---

src/main/java/uk/gov/cshr/controller/account/password/ChangePasswordController.java

This change changes the URL CSL redirects to when a user changes their password.

Hotfix: LC2662: Fix error when user changes their password

---

src/main/java/uk/gov/cshr/controller/ListIdentitiesController.java
src/main/java/uk/gov/cshr/dto/IdentityDTO.java
src/main/java/uk/gov/cshr/repository/IdentityRepository.java

- Add extra IdentityDTO fields to normalised identity repository function

LC-2477 'Free agent' users

---

azure-pipelines.yml
src/main/java/uk/gov/cshr/controller/account/password/ChangePasswordController.java

This change:
* Fixes the issue that shows an error when a user changes their password
* Introduces Azure Pipelines file

LC-2662: Hotfix: Password change bug fix

---

src/main/java/uk/gov/cshr/service/CompoundRole.java
src/main/java/uk/gov/cshr/service/CompoundRoleRepository.java
src/main/java/uk/gov/cshr/service/CompoundRoleRepositoryImpl.java
src/main/java/uk/gov/cshr/service/EmailUpdateService.java
src/main/java/uk/gov/cshr/service/ICompoundRole.java
src/main/java/uk/gov/cshr/service/security/IdentityService.java

Reverts Civil-Service-Human-Resources/identity-service#253

Revert "Revert "LC-2863 Remove reporting roles when changing email address""
